EXTRAFLAGS = 

PACKAGE = constprop

CPPSRCS = constant.cc # add your other .cc files here 

CPPHDRS = constant.h ConstPropWS.h # add your other .h files here 

OTHERSRCS = Makefile 

include ../config/Rules.make
